language: node_js
node_js:
 - "node"
before_install:
 - npm install -g yarn
 - psql -c 'create database node_ddd_test;' -U postgres
install:
 - yarn
after_script:
 - npm run coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
cache:
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
